# Numpy Exercises
# =========================

In [1]:
import numpy as np

In [3]:
def one():
    return np.array(range(100))

In [46]:
def two():
    '''
    INPUT: NONE
    OUTPUT: A column vector of 100 sequential floats all between 0 and 50. (matrix)
    Create a column vector with numpy (100 x 1).
    Example:
    >>>
    >>> cv = two()
    >>> print cv
    >>> [[  0.        ]
         [  0.50505051]
         [  1.01010101]
         ...
          [ 50.        ]]
    '''
    return np.linspace(0,50,num=100)


In [57]:
def three():
    '''
    INPUT: NONE
    OUTPUT: A 6 x 6 numpy matrix
    Create a square 6 by 6 matrix
    Example:
    >>>
    >>> M = three()
    >>> print M
    >>> [[ 0  1  2  3  4  5]
         [ 6  7  8  9 10 11]
         [12 13 14 15 16 17]
         [18 19 20 21 22 23]
         [24 25 26 27 28 29]
         [30 31 32 33 34 35]]
    '''
    return np.arange(36).reshape(6,6)



In [24]:
def four():
    '''
    INPUT: NONE
    OUTPUT: A random 2 x 3 numpy matrix
    Create a random 2 x 3 matrix.
    You should be able to do this with one command  (look at the numpy random module).
    Example:
    >>>
    >>> M = four()
    >>> print M
    >>> [[7 8 2]
         [9 4 3]]
    '''
    return np.random.rand(2,3)


In [25]:
def five():
    '''
    Create a 6 x 6 identity matrix.
    INPUT: NONE
    OUTPUT: 6 x 6 identity matrix
    Example:
    >>> I = five()
    >>> print I
    >>> [[ 1.  0.  0.  0.  0.  0.]
         [ 0.  1.  0.  0.  0.  0.]
         [ 0.  0.  1.  0.  0.  0.]
         [ 0.  0.  0.  1.  0.  0.]
         [ 0.  0.  0.  0.  1.  0.]
         [ 0.  0.  0.  0.  0.  1.]]
    '''
    return np.eye(6)


In [64]:
def six():
    '''
    Create a (10 x 10) matrix with sequential ints 0 through 99.
    Example:
    >>> print answer
    >>>> [[ 0  1  2  3  4  5  6  7  8  9]
          [10 11 12 13 14 15 16 17 18 19]
          [20 21 22 23 24 25 26 27 28 29]
          [30 31 32 33 34 35 36 37 38 39]
          [40 41 42 43 44 45 46 47 48 49]
          [50 51 52 53 54 55 56 57 58 59]
          [60 61 62 63 64 65 66 67 68 69]
          [70 71 72 73 74 75 76 77 78 79]
          [80 81 82 83 84 85 86 87 88 89]
          [90 91 92 93 94 95 96 97 98 99]]
    '''
#     lst = range(100)
#     return np.array([lst[i*10:i*10+10] for i in range(10)])
    return np.arange(100).reshape(10,10)

In [65]:
def seven():
    '''
    INPUT: Matrix output from function six.
    OUTPUT:  First three columns of Matrix from function six.
    Call function six() and save it as M,
    Return just the first 3 columns of M
    Example:
    >>> M = six()
    >>> print seven(M)
    >>> [[ 0  1  2]
         [10 11 12]
         [20 21 22]
         [30 31 32]
         [40 41 42]
         [50 51 52]
         [60 61 62]
         [70 71 72]
         [80 81 82]
         [90 91 92]]
    '''
    matrix_six = six()
    return matrix_six[:,:3]
    

In [66]:
def eight():
    '''
    INPUT: Matrix output from function six.
    OUTPUT:  Last two ROWS of Matrix from function six.
    Example:
    >>> M = six()
    >>> print eight(M)
    >>> [[80 81 82 83 84 85 86 87 88 89]
         [90 91 92 93 94 95 96 97 98 99]]
    '''
    matrix_six = six()
    return matrix_six[-2: , :]

# PART 2: SCALAR OPERATIONS
# =========================


In [61]:
def nine():
    '''
    INPUT: None
    OUTPUT: A numpy array with values [ [0,1,2,3,4,5,6,7,8,9] ]
    Create this numpy array (called V): [ [0,1,2,3,4,5,6,7,8,9] ]
    '''
    V = np.array(range(10))
    return V
    

In [69]:
def ten(V):
    '''
    INPUT: V ( matrix from nine() )
    OUTPUT: [[ 0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5]]
    Do a scalar addition by 0.5 to V.
    '''
    return V + 0.5
    

In [72]:
def eleven(V):
    '''
    INPUT: V (matrix from nine() )
    Do a scalar multiple by -2.
    OUTPUT:  [[  0  -2  -4  -6  -8 -10 -12 -14 -16 -18]]
    '''
    return V * -2

In [ ]:
def twelve(V):
    '''
    INPUT: V ( matrix from nine() )
    OUTPUT: answer = V+B
    Create a 1 by 10 vector 'B',
    that when added to V,  will yeild the same results as function ten
    V + B = [[ 0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5]]
    Return your answer
    '''
     return np.full((1,10),0.5)

In [67]:
V = np.array(range(10))

In [70]:
V * -2.

array([ -0.,  -2.,  -4.,  -6.,  -8., -10., -12., -14., -16., -18.])

In [76]:
np.ones((1,10))/2

array([[ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5]])

In [78]:
np.linspace(0.5,0.5,10)

array([ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5])

In [79]:
np.full((1,10),0.5)

array([[ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5]])

# PART 3: MATRIX / VECTOR Multiplication
# ======================================

In [106]:
def thirteen():
    '''
    Create column vector with 3 ints, called as column_vector.
    Create a row vector with 3 ints, called as row_vector.
    Create 3 x 3 square matrix called and square_matrix:
    Return as column_vector, row_vector, square_matrix (IN THAT ORDER)
    '''
    column_vector = np.reshape(np.arange(0,3) , (3,1))
    row_vector = np.arange(10,13)
    square_matrix = np.reshape(np.arange(9) , (3,3))
    return column_vector, row_vector, square_matrix

In [107]:
square_matrix = np.reshape(np.arange(9) , (3,3))

In [108]:
square_matrix


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [102]:
column_vector = np.reshape(np.arange(0,3) , (1,3))

In [105]:
np.reshape(column_vector, (3,1))

array([[0],
       [1],
       [2]])

In [98]:
column_vector, row_vector, square_matrix = thirteen()

In [114]:
row_vector = np.arange(10,13)


In [115]:
row_vector

array([10, 11, 12])

In [129]:

def fourteen(column_vector, row_vector):
    '''
    INPUT: Using column_vector and row_vector from thirteen() as the inputs
    OUTPUT:  n x m shaped vector where n is number of rows in row_vector and m is number of cols in col_vec
    Perform a vector vector multiply on column_vector and row_vector.
    This should output a n x m matrix where n is the number of rows in row_vector and m is the number of columns in column_vector.
    Say column_vector is a 2 x 1 and row_vector is a 1 x 3, output will be a 2 x 3 matrix.
    '''
    column_vector * row_vector
    

In [121]:
column_vector, row_vector, square_matrix = thirteen()
n = row_vector.shape[0]
m = column_vector.shape[1]

In [122]:
n

3

In [125]:
m

1

In [126]:
column_vector

array([[0],
       [1],
       [2]])

In [128]:
row_vector

array([10, 11, 12])

In [124]:
column_vector * row_vector

array([[ 0,  0,  0],
       [10, 11, 12],
       [20, 22, 24]])

In [130]:
def fifteen(column_vector, row_vector, square_matrix):
    '''
    INPUT: Using column_vector and row_vector from thirteen() as the inputs
    OUTPUT:  return c_answer, r_answer
    c_answer is the matrix multiplication of column_vector and square_matrix
    r_answer is the matrix multiplication of row_vector and square_matrix
    For both column_vector and row_vector, matrix multiply by square_matrix.
    One will have to go on the left and one will have to go on the right.
    If it lets you do both directions,
        you probably are doing elementwise multiplication instead of matrix multiplication!
    Make sure you return c_answer first
    return c_answer, r_answer
    '''
    
